In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    mean_squared_error,
    r2_score,
    confusion_matrix,
    classification_report,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_curve,
    roc_auc_score
)

In [2]:
df = pd.read_csv("../outputs/cleaned_data.csv")

df.head()

,PatientID,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,...,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness,Diagnosis,DoctorInCharge
0,4751,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,...,0,0,1.725883,0,0,0,1,0,0,XXXConfid
1,4752,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,...,0,0,2.592424,0,0,0,0,1,0,XXXConfid
2,4753,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,...,0,0,7.119548,0,1,0,1,0,0,XXXConfid
3,4754,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,...,0,1,6.481226,0,0,0,0,0,0,XXXConfid
4,4755,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,...,0,0,0.014691,0,0,1,1,0,0,XXXConfid

In [3]:
print(df.shape)

print(df.columns)

(2149, 35)
Index(['PatientID', 'Age', 'Gender', 'Ethnicity', 'EducationLevel', 'BMI',
       'Smoking', 'AlcoholConsumption', 'PhysicalActivity', 'DietQuality',
       'SleepQuality', 'FamilyHistoryAlzheimers', 'CardiovascularDisease',
       'Diabetes', 'Depression', 'HeadInjury', 'Hypertension', 'SystolicBP',
       'DiastolicBP', 'CholesterolTotal', 'CholesterolLDL', 'CholesterolHDL',
       'CholesterolTriglycerides', 'MMSE', 'FunctionalAssessment',
       'MemoryComplaints', 'BehavioralProblems', 'ADL', 'Confusion',
       'Disorientation', 'PersonalityChanges', 'DifficultyCompletingTasks',
       'Forgetfulness', 'Diagnosis', 'DoctorInCharge'],
      dtype='str')

In [4]:
y_reg = df["MMSE"]

In [5]:
y_clf = df["Diagnosis"]

In [6]:
X = df.drop(columns=["MMSE", "Diagnosis"])

In [7]:
print(X.shape)
print(y_reg.shape)
print(y_clf.shape)

(2149, 33)
(2149,)
(2149,)

In [8]:
X.dtypes

PatientID                      int64
Age                            int64
Gender                         int64
Ethnicity                      int64
EducationLevel                 int64
BMI                          float64
Smoking                        int64
AlcoholConsumption           float64
PhysicalActivity             float64
DietQuality                  float64
SleepQuality                 float64
FamilyHistoryAlzheimers        int64
CardiovascularDisease          int64
Diabetes                       int64
Depression                     int64
HeadInjury                     int64
Hypertension                   int64
SystolicBP                     int64
DiastolicBP                    int64
CholesterolTotal             float64
CholesterolLDL               float64
CholesterolHDL               float64
CholesterolTriglycerides     float64
FunctionalAssessment         float64
MemoryComplaints               int64
BehavioralProblems             int64
ADL                          float64
Confusion                      int64
Disorientation                 int64
PersonalityChanges             int64
DifficultyCompletingTasks      int64
Forgetfulness                  int64
DoctorInCharge                   str
dtype: object

In [9]:
X = df.drop(columns=[
    "PatientID",
    "DoctorInCharge",
    "MMSE",
    "Diagnosis"
])

X.head()

,Age,Gender,Ethnicity,EducationLevel,BMI,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,...,CholesterolTriglycerides,FunctionalAssessment,MemoryComplaints,BehavioralProblems,ADL,Confusion,Disorientation,PersonalityChanges,DifficultyCompletingTasks,Forgetfulness
0,73,0,0,2,22.927749,0,13.297218,6.327112,1.347214,9.025679,...,162.189143,6.518877,0,0,1.725883,0,0,0,1,0
1,89,0,0,0,26.827681,0,4.542524,7.619885,0.518767,7.151293,...,294.630909,7.118696,0,0,2.592424,0,0,0,0,1
2,73,0,3,1,17.795882,0,19.555085,7.844988,1.826335,9.673574,...,83.638324,5.895077,0,0,7.119548,0,1,0,1,0
3,74,1,0,1,33.800817,1,12.209266,8.428001,7.435604,8.392554,...,277.577358,8.965106,0,1,6.481226,0,0,0,0,0
4,89,0,0,0,20.716974,0,18.454356,6.310461,0.795498,5.597238,...,291.198780,6.045039,0,0,0.014691,0,0,1,1,0

In [10]:
print(X.select_dtypes(include=["object"]).columns)

Index([], dtype='str')

In [11]:
print(X.select_dtypes(include=["category"]).columns)

Index([], dtype='str')

In [13]:
from sklearn.model_selection import train_test_split

# Regression
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X,
    y_reg,
    test_size=0.2,
    random_state=42
)

# Classification
X_train_clf, X_test_clf, y_train_clf, y_test_clf = train_test_split(
    X,
    y_clf,
    test_size=0.2,
    random_state=42
)

In [14]:
print(X_train_reg.shape)
print(X_test_reg.shape)

print(y_train_reg.shape)
print(y_test_reg.shape)

(1719, 31)
(430, 31)
(1719,)
(430,)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_reg_scaled = scaler.fit_transform(X_train_reg)
X_test_reg_scaled = scaler.transform(X_test_reg)

X_train_clf_scaled = scaler.fit_transform(X_train_clf)
X_test_clf_scaled = scaler.transform(X_test_clf)

In [16]:
print(X.select_dtypes(include=["object"]).columns)

Index([], dtype='str')

In [17]:
print(X_train_reg.shape)
print(X_test_reg.shape)

(1719, 31)
(430, 31)

In [18]:
from sklearn.linear_model import LinearRegression

linear_model = LinearRegression()

linear_model.fit(X_train_reg_scaled, y_train_reg)

LinearRegression()

In [19]:
y_pred_reg = linear_model.predict(X_test_reg_scaled)

print(y_pred_reg[:10])

[14.46888588 13.21786204 15.13213139 14.64577263 14.3334496  14.11459053
 13.66407687 14.07169256 13.93962883 15.27031408]

In [20]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test_reg, y_pred_reg)
r2 = r2_score(y_test_reg, y_pred_reg)

print("Mean Squared Error (MSE):", mse)
print("R² Score:", r2)

Mean Squared Error (MSE): 73.50948217096867
R² Score: -0.015658404529612868

In [21]:
coefficients = pd.DataFrame({
    "Feature": X.columns,
    "Coefficient": linear_model.coef_
})

coefficients

                      Feature  Coefficient
0                         Age    -0.121345
1                      Gender     0.133002
2                   Ethnicity    -0.022000
3              EducationLevel     0.122410
4                         BMI     0.018226
5                     Smoking     0.086563
6          AlcoholConsumption    -0.137069
7            PhysicalActivity    -0.026650
8                 DietQuality     0.134718
9                SleepQuality     0.168043
10    FamilyHistoryAlzheimers     0.012481
11      CardiovascularDisease     0.290329
12                   Diabetes    -0.339047
13                 Depression     0.055583
14                 HeadInjury     0.023135
15               Hypertension     0.175739
16                 SystolicBP     0.044085
17                DiastolicBP    -0.322870
18           CholesterolTotal    -0.003748
19             CholesterolLDL     0.176153
20             CholesterolHDL     0.046743
21   CholesterolTriglycerides     0.137791
22       FunctionalAssessment     0.206324
23           MemoryComplaints     0.105021
24         BehavioralProblems     0.112163
25                        ADL     0.010913
26                  Confusion     0.112982
27             Disorientation     0.276849
28         PersonalityChanges     0.210299
29  DifficultyCompletingTasks     0.139378
30              Forgetfulness    -0.064774

In [22]:
top3 = coefficients.reindex(
    coefficients["Coefficient"].abs().sort_values(ascending=False).index
).head(3)

print(top3)

                  Feature  Coefficient
12               Diabetes    -0.339047
17            DiastolicBP    -0.322870
11  CardiovascularDisease     0.290329

In [23]:
from sklearn.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)

ridge_model.fit(X_train_reg_scaled, y_train_reg)

y_pred_ridge = ridge_model.predict(X_test_reg_scaled)

ridge_mse = mean_squared_error(y_test_reg, y_pred_ridge)

ridge_r2 = r2_score(y_test_reg, y_pred_ridge)

print("Ridge Regression")
print("MSE:", ridge_mse)
print("R²:", ridge_r2)

Ridge Regression
MSE: 73.50834496366933
R²: -0.015642692078414067

In [24]:
comparison = pd.DataFrame({
    "Model": ["Linear Regression", "Ridge Regression"],
    "MSE": [mse, ridge_mse],
    "R²": [r2, ridge_r2]
})

comparison

               Model        MSE        R²
0  Linear Regression  73.509482 -0.015658
1   Ridge Regression  73.508345 -0.015643

# Part 2 – Supervised Machine Learning

## 1. Import Libraries

## 2. Load Cleaned Dataset

## 3. Define Features and Targets

## 4. Data Preprocessing

## 5. Linear Regression

## 6. Ridge Regression

## 7. Logistic Regression

In [25]:
print("Training Class Distribution")
print(y_train_clf.value_counts())

print("\nPercentage")
print(y_train_clf.value_counts(normalize=True) * 100)

Training Class Distribution
Diagnosis
0    1112
1     607
Name: count, dtype: int64

Percentage
Diagnosis
0    64.688773
1    35.311227
Name: proportion, dtype: float64

In [26]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(max_iter=1000)

log_model.fit(X_train_clf_scaled, y_train_clf)

LogisticRegression(max_iter=1000)

In [27]:
y_pred_clf = log_model.predict(X_test_clf_scaled)

y_pred_prob = log_model.predict_proba(X_test_clf_scaled)[:, 1]

In [28]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_clf, y_pred_clf)

print(cm)

[[245  32]
 [ 57  96]]

In [29]:
from sklearn.metrics import classification_report

print(classification_report(y_test_clf, y_pred_clf))

              precision    recall  f1-score   support

           0       0.81      0.88      0.85       277
           1       0.75      0.63      0.68       153

    accuracy                           0.79       430
   macro avg       0.78      0.76      0.76       430
weighted avg       0.79      0.79      0.79       430

In [30]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

accuracy = accuracy_score(y_test_clf, y_pred_clf)
precision = precision_score(y_test_clf, y_pred_clf)
recall = recall_score(y_test_clf, y_pred_clf)
f1 = f1_score(y_test_clf, y_pred_clf)

print("Accuracy :", accuracy)
print("Precision:", precision)
print("Recall   :", recall)
print("F1 Score :", f1)

Accuracy : 0.7930232558139535
Precision: 0.75
Recall   : 0.6274509803921569
F1 Score : 0.6832740213523132

In [ ]:
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score

fpr, tpr, thresholds = roc_curve(y_test_clf, y_pred_prob)

auc = roc_auc_score(y_test_clf, y_pred_prob)

print("AUC:", auc)

plt.figure(figsize=(6,5))
plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}")
plt.plot([0,1], [0,1], linestyle="--")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.legend()
plt.show()

In [ ]:
thresholds = [0.30, 0.40, 0.50, 0.60, 0.70]

results = []

for t in thresholds:
    preds = (y_pred_prob >= t).astype(int)

    p = precision_score(y_test_clf, preds)
    r = recall_score(y_test_clf, preds)
    f = f1_score(y_test_clf, preds)

    results.append([t, p, r, f])

threshold_table = pd.DataFrame(
    results,
    columns=["Threshold", "Precision", "Recall", "F1"]
)

threshold_table